spec:
  template:
    spec:
      containers:
        - env:
          - name: OPENSHIFT_API_URL
            value: ${OPENSHIFT_API_URL}
          - name: KEYCLOAK_SAAS_URL
            value: http://sso.prod-preview.openshift.io
          workingDir: /home
          readinessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 3
            httpGet:
              path: "forge/version"
              port: 8080
          livenessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 120
            failureThreshold: 10
            httpGet:
              path: "forge/version"
              port: 8080
        serviceAccountName: "${project.artifactId}"