spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: KEYCLOAK_SAAS_URL
          value: http://sso.prod-preview.openshift.io
      serviceAccountName: "${project.artifactId}"