apiVersion: v1
kind: Route
metadata:
  name: generator-backend
  labels:
    app: generator-backend
spec:
  to:
    kind: Service
    name: generator-backend
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect